[package]
name = "lumen"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["winit", "wgpu", "std"]
std = []
winit = ["dep:winit"]
wgpu = ["dep:wgpu"]
embedded = ["no_std"]
no_std = []

[dependencies]
wgpu = { workspace = true, optional = true }
winit = { workspace = true, optional = true, features = ["rwh_06"] }
cosmic-text = { workspace = true }
mint.workspace = true
log.workspace = true
smol_str.workspace = true
hashbrown.workspace = true
ahash.workspace = true
rustc-hash.workspace = true
smallvec.workspace = true
bitflags.workspace = true
bytemuck.workspace = true
once_cell.workspace = true
pollster = "0.3"

[target.'cfg(target_os = "linux")'.dependencies]
winit = { workspace = true, optional = true, features = ["x11", "rwh_06"] }

[dev-dependencies]
env_logger = "0.11"
criterion = { version = "0.5", default-features = false, features = ["plotters"] }

[[bench]]
name = "layout"
harness = false
[[bench]]
name = "render"
harness = false
[[bench]]
name = "widgets"
harness = false

[[example]]
name = "counter"
path = "../../examples/counter.rs"
[[example]]
name = "gallery"
path = "../../examples/gallery.rs"
[[example]]
name = "stress"
path = "../../examples/stress.rs"
[[example]]
name = "themes"
path = "../../examples/themes.rs"
[[example]]
name = "icons"
path = "../../examples/icons.rs"
